# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.xci
# IP: The module: 'pll1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.xci
# IP: The module: 'pll1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
