# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.cache/wt} [current_project]
set_property parent.project_path {E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet {{e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.dcp}}
set_property used_in_implementation false [get_files {{e:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/ip/pll1/pll1.dcp}}]
read_verilog -library xil_defaultlib {
  {E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/new/shift_register.v}
  {E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/new/pulse_generator.v}
  {E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/sources_1/new/preprocessing_top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/constrs_1/imports/zedboard_master_XDC_RevC_D_v2/zedboard_master_XDC_RevC_D_v2.xdc}}
set_property used_in_implementation false [get_files {{E:/HASP/GRID Redesign/Code/Preprocessing2/Preprocessing2.srcs/constrs_1/imports/zedboard_master_XDC_RevC_D_v2/zedboard_master_XDC_RevC_D_v2.xdc}}]


synth_design -top preprocessing_top -part xc7z020clg484-1


write_checkpoint -force -noxdef preprocessing_top.dcp

catch { report_utilization -file preprocessing_top_utilization_synth.rpt -pb preprocessing_top_utilization_synth.pb }
